// Every bundled puzzle: valid shape, colours, original-art metadata, and a UNIQUE solution reachable by line logic.
// Run: node test/puzzles.test.js
const assert = require('assert');
const L = require('../www/js/logic.js');
const D = require('../www/js/puzzles.js');
let pass = 0, fail = 0;
function t(name, fn) { try { fn(); pass++; console.log('  ok -', name); } catch (e) { fail++; console.log('  FAIL -', name, '\n   ', e.message); } }
const all = D.packs.flatMap(p => p.puzzles.map(q => Object.assign({ pack: p.id }, q)));

console.log('puzzles.test.js');
t('at least 300 puzzles in themed packs', () => { assert.ok(all.length >= 300, all.length + ' puzzles'); assert.ok(D.packs.length >= 8); D.packs.forEach(p => assert.ok(p.name && p.desc && p.puzzles.length >= 20, p.id)); });
t('sizes span 5x5 to 20x20', () => {
  const sizes = new Set(all.map(p => p.w + 'x' + p.h));
  ['5x5', '8x8', '10x10', '12x12', '15x15', '20x20'].forEach(s => assert.ok(sizes.has(s), 'has ' + s));
  all.forEach(p => { assert.ok(p.w >= 5 && p.w <= 20 && p.h >= 5 && p.h <= 20); assert.strictEqual(p.rows.length, p.h); p.rows.forEach(r => assert.strictEqual(r.length, p.w, p.id)); });
});
t('ids unique and stable format, names present', () => {
  const ids = new Set(); all.forEach(p => { assert.ok(/^[a-z]+-\d{2}$/.test(p.id), p.id); assert.ok(!ids.has(p.id)); ids.add(p.id); assert.ok(p.name && p.name.length < 30); });
});
t('every filled cell has a palette colour; pictures are neither empty nor full', () => {
  all.forEach(p => {
    let f = 0; p.rows.join('').split('').forEach(ch => { if (ch !== '.') { f++; assert.ok(D.palette[ch], p.id + ' colour ' + ch); } });
    const r = f / (p.w * p.h); assert.ok(r >= 0.1 && r <= 0.92, p.id + ' fill ' + r.toFixed(2));
  });
});
t('no two puzzles share the same solution', () => { const s = new Set(); all.forEach(p => { const k = p.w + 'x' + p.h + p.rows.join('').replace(/[^.]/g, '#'); assert.ok(!s.has(k), 'duplicate ' + p.id); s.add(k); }); });
t('EVERY puzzle is solved from its clues by the line solver alone (=> unique solution)', () => {
  let rounds = 0;
  all.forEach(p => {
    const { sol } = L.parsePuzzle(p), cl = L.cluesOf(sol, p.w, p.h), res = L.lineSolve(cl.rows, cl.cols);
    assert.ok(res.solved && !res.contradiction, p.id + ' not line-solvable');
    assert.deepStrictEqual(res.grid, sol, p.id + ' solved to a different picture');
    rounds += res.rounds;
  });
  console.log('     (' + all.length + ' puzzles verified, avg ' + (rounds / all.length).toFixed(1) + ' line-solving sweeps)');
});
t('independent uniqueness check: backtracking counter finds exactly 1 solution for every 5x5 and 8x8 puzzle', () => {
  all.filter(p => p.w <= 8).forEach(p => { const { sol } = L.parsePuzzle(p), cl = L.cluesOf(sol, p.w, p.h); assert.strictEqual(L.countSolutions(cl.rows, cl.cols, 2), 1, p.id); });
});
t('puzzle data matches a fresh deterministic build (tools/build-puzzles.js output is committed)', () => {
  const src = require('fs').readFileSync(__dirname + '/../www/js/puzzles.js', 'utf8');
  assert.ok(src.startsWith('/* GENERATED by tools/build-puzzles.js'));
});
console.log(`\n${pass} passed, ${fail} failed`);
if (fail) process.exit(1);
