// Hand-drawn original pixel art for the small packs. '.' = empty, letters = palette colours (see palette.js).
module.exports.S5 = [
  ['Heart', '.r.r.', 'rrrrr', 'rrrrr', '.rrr.', '..r..'],
  ['Arrow', '..b..', '.bbb.', 'b.b.b', '..b..', '..b..'],
  ['Little house', '..m..', '.mmm.', 'mmmmm', '.t.t.', '.ttt.'],
  ['Sprout', 'g...g', 'gg.gg', '.ggg.', '..n..', '.nnn.'],
  ['Cup', 'wwww.', 'w..ww', 'w..w.', 'www..', '.....'],
  ['Key', 'yy...', 'y.yyy', 'yy.y.', '.....', '.....'],
  ['Plus', '..r..', '..r..', 'rrrrr', '..r..', '..r..'],
  ['Mushroom', '.rrr.', 'rwrwr', 'rrrrr', '.ww..', '.ww..'],
  ['Tree', '..g..', '.ggg.', 'ggggg', '..n..', '..n..'],
  ['Fish', '.bb.b', 'bbbbb', 'b.bb.', 'bbbbb', '.bb.b'],
  ['Moon', '.yy..', 'yy...', 'yy...', 'yy...', '.yy..'],
  ['Bell', '..y..', '.yyy.', '.yyy.', 'yyyyy', '..y..'],
  ['Cherry', '..g.g', '.g..g', 'r..rr', 'rr.rr', 'rr...'],
  ['Smile', '.k.k.', '.k.k.', '.....', 'k...k', '.kkk.'],
  ['Boat', '..w..', '..ww.', '..w..', 'nnnnn', '.nnn.'],
  ['Umbrella', '.ppp.', 'ppppp', '..n..', '..n..', '.nn..'],
  ['Diamond', '..c..', '.ccc.', 'ccccc', '.ccc.', '..c..'],
  ['Hourglass', 'ttttt', '.ttt.', '..t..', '.ttt.', 'ttttt'],
  ['Note', '..kk.', '..k.k', '..k..', 'kkk..', 'kkk..'],
  ['Crown', 'y.y.y', 'yyyyy', 'yryry', 'yyyyy', '.....'],
  ['Flag', 'rrrr.', 'rrrr.', 'k....', 'k....', 'k....'],
  ['Stairs', '....o', '...oo', '..ooo', '.oooo', 'ooooo'],
  ['Snail', '.ooo.', 'o.o.o', 'oo.oo', '.ooo.', 'ggggg'],
  ['Leaf', '...gg', '..ggg', '.ggg.', 'ggg..', 'g....'],
  ['Envelope', 'wwwww', 'ww.ww', 'w.w.w', 'w...w', 'wwwww'],
  ['Lamp', '.yyy.', 'yyyyy', '..k..', '..k..', '.kkk.'],
  ['Sun', 'y.y.y', '.yyy.', 'yyyyy', '.yyy.', 'y.y.y'],
  ['Rain', '.sss.', 'sssss', '.....', 'b.b.b', '.b.b.'],
  ['Candle', '..o..', '..y..', '.www.', '.www.', 'wwwww'],
  ['Duckling', '.yy..', 'yyko.', '.yy..', 'yyyy.', '.yyy.'],
  ['Castle', 's.s.s', 'sssss', 'ss.ss', 'ss.ss', 'sssss'],
  ['Pine', '..G..', '.GGG.', '..G..', '.GGG.', 'GGGGG'],
  ['Kite', '..p..', '.ppp.', 'ppppp', '.ppp.', '..k.k'],
  ['Dice', 'wwwww', 'wk.kw', 'ww.ww', 'wk.kw', 'wwwww']
];
module.exports.S8 = [
  ['Cat face', 'o.....o.', 'oo...oo.', 'ooooooo.', 'o.ooo.o.', 'ooooooo.', 'oookooo.', '.ooooo..', '........'],
  ['Teacup', '..s..s..', '...s..s.', '........', 'wwwwwww.', 'wwwwwwww', 'wwwwww.w', '.wwwwww.', 'tttttttt'],
  ['Strawberry', '..g.g...', '.ggggg..', 'rrrrrrr.', 'rryrryr.', 'rrrrrrr.', '.ryrrr..', '..rrr...', '...r....'],
  ['Rocket', '...rr...', '..wwww..', '..wbbw..', '..wwww..', '..wwww..', '.rwwwwr.', 'rr.oo.rr', '...oo...'],
  ['Ice cream', '..PPP...', '.PPPPP..', '.PPPPP..', '.ttttt..', '..ttt...', '..ttt...', '...t....', '...t....'],
  ['Bird', '..bbb...', '.bbkbb..', 'bbbbbbo.', 'bbbbbb..', '.bbbbbbb', '..bbbb..', '...o.o..', '..oo.oo.'],
  ['Anchor', '...kk...', '..k..k..', '...kk...', 'kkkkkkkk', '...kk...', 'k..kk..k', 'kk.kk.kk', '.kkkkkk.'],
  ['Watermelon', '........', 'GGGGGGGG', 'lrrrrrrl', '.rrkrkr.', '.lrrrrl.', '..lrrl..', '...ll...', '........'],
  ['Owl', 'n.nnnn.n', 'nnnnnnnn', 'nwwnnwwn', 'nwknnkwn', 'nnnoonnn', '.nnttnn.', '.nnttnn.', '..o..o..'],
  ['Lighthouse', '...yy...', '..kkkk..', '...rr...', '...ww...', '..rrrr..', '..wwww..', '.rrrrrr.', 'bbbbbbbb'],
  ['Butterfly', 'pp....pp', 'ppp..ppp', 'pyppppyp', 'pppkkppp', '.ppkkpp.', 'pp.kk.pp', 'pp....pp', '........'],
  ['Mug', '........', '.wwwww..', '.wrwrwww', '.wwwww.w', '.wrwrwww', '.wwwww..', '.wwwww..', '........'],
  ['Turtle', '...GG...', '..GgGG..', '.GGgGGGg', 'gGGGgGG.', '.GgGGgG.', 'g.g..g.g', '........', '........'],
  ['Clover', '.gg.gg..', 'gggggg..', 'gggggg..', '.gggg...', 'gggggg..', 'gg.ggg..', '....g...', '.....g..'],
  ['Apple', '....n...', '...ng...', '.rrnrr..', 'rrrrrrr.', 'rrrrrrr.', 'rrrrrrr.', '.rrrrr..', '..r.r...'],
  ['Star', '...yy...', '...yy...', 'yyyyyyyy', '.yyyyyy.', '..yyyy..', '.yyyyyy.', '.yy..yy.', 'yy....yy'],
  ['Cactus', '...gg...', '.g.gg...', '.g.gg.g.', '.ggggg.g', '...ggggg', '...gg...', '.oooooo.', '..oooo..'],
  ['Sailboat', '...w....', '...ww...', '..www...', '..wwww..', '.wwwww..', '...k....', 'nnnnnnn.', '.nnnnn..'],
  ['Balloon', '..rrr...', '.rrrrr..', '.rwrrr..', '.rrrrr..', '..rrr...', '...r....', '...k....', '....k...'],
  ['Snowman', '...kk...', '..kkkk..', '..wwww..', '..wkkw..', '..wwww..', '.wwwwww.', 'wwwkwwww', '.wwwwww.'],
  ['Key ring', '.yyy....', 'y...y...', 'y...y...', '.yyyyyyy', '.....y.y', '.....y.y', '........', '........'],
  ['Pear', '....n...', '...ll...', '...ll...', '..llll..', '.llllll.', '.llllll.', '.llllll.', '..llll..']
];
